version: '3.8'

services:
  web:
    build: .
    container_name: gameenad-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: gameenad-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gameenad
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
